### ISSUE TITLE
Crashes immediately after playing

### ISSUE THREAD

**Issue by ZeeshanSultan** [meik97/XSpotify#3] opened 2020-01-24 02:26 UTC
When running it immediately crashes after i play a song and track id is displayed in the console. I am using the latest spotify client (1.1.24.91.g4ca6d5eb)

**Comment by meik97** [comment] 2020-01-24 04:59
Hey ZeeshanSultan,

have you tried to switch the song before you start to play one ?

Let me explain it in a few steps:
1. Start XSpotify
2. Do NOT click on play
3. Switch to another song or playlist
4. Start your song / let the song start automatically

**Comment by YouAreGay** [comment] 2020-01-24 14:46
Still crashes when i play a song for longer then a sec.

**Comment by meik97** [comment] 2020-01-24 14:58
The adblock should work without the token creator.

Did you try the steps i have mentioned above @YouAreGay ?

**Comment by YouAreGay** [comment] 2020-01-24 15:00
> 
> 
> The adblock should work without the token creator.
> 
> Did you try the steps i have mentioned above @YouAreGay ?

yes tried it. sadly didnt worked. @meik97

**Comment by meik97** [comment] 2020-01-24 15:07
Here are a few things you can check / try:

1. Latest spotify version (1.1.24.91.g4ca6d5eb)
2. Admin rights (read and write to your Spotify folder)
3. Start XSpotify after you have started Spotify (or the other way around)
4. If possible - try a diffrent computer

**Comment by 2ez4kobezxc** [comment] 2020-01-24 19:24
Same to me, my console automatically close after a few seconds

**Comment by farrasrayhand** [comment] 2020-01-25 05:11
not work, force close after play

**Comment by DrOreo002** [comment] 2020-01-25 07:11
Same, it closes automatically when I start it

**Comment by vipertrek79** [comment] 2020-01-26 17:19
> Here are a few things you can check / try:
> 
> 1. Latest spotify version (1.1.24.91.g4ca6d5eb)
> 2. Admin rights (read and write to your Spotify folder)
> 3. Start XSpotify after you have started Spotify (or the other way around)
> 4. If possible - try a diffrent computer

Had the instant crashing issue. Giving admin rights to my spotify folder fixed it :) Thanks!

**Comment by pablo-gil-m** [comment] 2020-01-26 17:45
Same bug happening to me, version 1.1.24.91.g4ca6d5eb

**Comment by bascurtiz** [comment] 2020-01-26 19:40
@ZeeshanSultan @YouAreGay @pablo-gil-m @DrOreo002 @farrasrayhand @2ez4kobezxc 
Are you guys using Premium account?
Since that crashed for me too. 
Using Free account however works.
See more info regarding quality too at #8

**Comment by HoneyOTU1337** [comment] 2020-01-26 22:26
happens to me as well. i have a free account

**Comment by shinji257** [comment] 2020-01-26 23:28
I'm also having the same issue.  Plays a song for about a second then bails completely.

Version: 1.1.24.91.g4ca6d5eb
Account Status: Free (it's also a new profile)
Tried loading Spotify then loading XSpotify
Tried giving Spotify admin rights then loading XSpotify
This is being tested inside a VM which is not the host system
Since the Windows 10 install is pretty basic I also installed the AIO redist package that was linked in the README.md file.
Since @YouAreGay said deleting token.exe worked for them I deleted it and tried again with the same crash happening.

I'm not sure what "giving admin rights to my spotify folder" that @vipertrek79 mentioned is referring to.

**Comment by deadair3210** [comment] 2020-01-27 02:13
Just tried the last posts advice, no dice. Still crashes after playing a second of the chosen song

**Comment by wefalltomorrow** [comment] 2020-01-27 02:33
[**@deadair3210**](https://github.com/deadair3210) commented on [27 Jan 2020, 13:13 GMT+11](https://github.com/meik97/XSpotify/issues/3#issuecomment-578570708 "2020-01-27T02:13:34Z - Replied by Github Reply Comments"):
> Just tried the last posts advice, no dice. Still crashes after playing a second of the chosen song

Same here, none of the solutions above work sadly.

**Comment by Ilomantis** [comment] 2020-01-27 05:26
Just chiming in to say I am experiencing the same problem. Latest spotify ver. (1.1.24.91.g4ca6d5eb) and injecting manually or using xspotify exe makes no difference. After playing a song it will crash after ~1 second.

**Comment by myFavShrimp** [comment] 2020-01-27 12:52
It worked for me after I disabled hardware acceleration in spotify settings but than it's very laggy

**Comment by The-Euphoria** [comment] 2020-01-27 14:00
> -snip-
> 1. Start Spotify.  You don't need to give it admin rights
> 2. Start playing a song.  During playback launch XSpotify.  At this point XSpotify will not launch.
> 3. Pause song and launch XSpotify again.  Now XSpotify launches.
> 4. Play a _different_ song.  Now it should (hopefully) work.
>    Now for the future you don't have to do this dance again.  Launching XSpotify directly should chain Spotify in and just work right away.

Thank you, shinji257, this worked for me. I'll report back if anything changes.

**Comment by pablo-gil-m** [comment] 2020-01-27 14:36
> I'm also having the same issue. Plays a song for about a second then bails completely.
> 
> Version: 1.1.24.91.g4ca6d5eb
> Account Status: Free (it's also a new profile)
> Tried loading Spotify then loading XSpotify
> Tried giving Spotify admin rights then loading XSpotify
> This is being tested inside a VM which is not the host system
> Since the Windows 10 install is pretty basic I also installed the AIO redist package that was linked in the README.md file.
> Since @YouAreGay said deleting token.exe worked for them I deleted it and tried again with the same crash happening.
> 
> I'm not sure what "giving admin rights to my spotify folder" that @vipertrek79 mentioned is referring to.
> 
> EDIT: I got it sorted and it is working now. Here is what I did. Some or all of the steps may be required and maybe it just decided to work at random.
> 
> 1. Start Spotify.  You don't need to give it admin rights
> 2. Start playing a song.  During playback launch XSpotify.  At this point XSpotify will not launch.
> 3. Pause song and launch XSpotify again.  Now XSpotify launches.
> 4. Play a _different_ song.  Now it should (hopefully) work.
>    Now for the future you don't have to do this dance again.  Launching XSpotify directly should chain Spotify in and just work right away.

Thanks, this worked for me too :)

**Comment by YouAreGay** [comment] 2020-01-27 14:36
This Worked for me
>     1. Start Spotify.  You don't need to give it admin rights
> 
>     2. Start playing a song.  During playback launch XSpotify.  At this point XSpotify will not launch.
> 
>     3. Pause song and launch XSpotify again.  Now XSpotify launches.
> 
>     4. Play a _different_ song.  Now it should (hopefully) work.
>        Now for the future you don't have to do this dance again.  Launching XSpotify directly should chain Spotify in and just work right away.
> 
But then this Problem occurs
>the pause and play button is lagged by like 10 seconds and the volume slider ceases to function.

**Comment by pablo-gil-m** [comment] 2020-01-27 14:39
> But then this Problem occurs
> 
> > the pause and play button is lagged by like 10 seconds and the volume slider ceases to function.

Yep same here

**Comment by The-Euphoria** [comment] 2020-01-27 14:52
> But then this Problem occurs
> 
> > the pause and play button is lagged by like 10 seconds and the volume slider ceases to function.

Yeah, same here, but it's working so I'll take it.

**Comment by farrasrayhand** [comment] 2020-01-27 14:59
> I'm also having the same issue. Plays a song for about a second then bails completely.
> 
> Version: 1.1.24.91.g4ca6d5eb
> Account Status: Free (it's also a new profile)
> Tried loading Spotify then loading XSpotify
> Tried giving Spotify admin rights then loading XSpotify
> This is being tested inside a VM which is not the host system
> Since the Windows 10 install is pretty basic I also installed the AIO redist package that was linked in the README.md file.
> Since @YouAreGay said deleting token.exe worked for them I deleted it and tried again with the same crash happening.
> 
> I'm not sure what "giving admin rights to my spotify folder" that @vipertrek79 mentioned is referring to.
> 
> EDIT: I got it sorted and it is working now. Here is what I did. Some or all of the steps may be required and maybe it just decided to work at random.
> 
> 1. Start Spotify.  You don't need to give it admin rights
> 2. Start playing a song.  During playback launch XSpotify.  At this point XSpotify will not launch.
> 3. Pause song and launch XSpotify again.  Now XSpotify launches.
> 4. Play a _different_ song.  Now it should (hopefully) work.
>    Now for the future you don't have to do this dance again.  Launching XSpotify directly should chain Spotify in and just work right away.

wow its work now

**Comment by meik97** [comment] 2020-01-27 15:32
The delay is caused by the download. As long as the download is not finished, you can not pause or switch the song. 

Im working on a fix!

**Comment by Ratchet601** [comment] 2020-01-27 16:11
Hey there, when the ads pop up it crashes and it doesnt want to launch when token.exe is deleted

**Comment by tarantinosaur** [comment] 2020-01-27 17:27
I already did all their solutions but mine still crashes when you play a song.

**Comment by deadair3210** [comment] 2020-01-27 18:21
Still getting the crash as well

**Comment by chris-kr** [comment] 2020-01-31 03:09
The above solution worked for me on release 1.0; however, on release 1.1:

- If XSpotify is launched with no other programs running, Spotify also launches but both programs crash within 1 second.
- If XSpotify is launched while Spotify is running and playing a song, XSpotify crashes but Spotify remains open.
- If XSpotify is launched while Spotify is running and not playing a song, both programs crash.

Have tried reinstalling after deleting %appdata%\Local\Spotify & AppData\Roaming\Spotify, no success.
This is on Windows 10 Pro, version 1909, build 18363.592. Spotify version is 1.1.25.559.g85cf5e4c.

**Comment by incheon-kim** [comment] 2020-02-03 20:46
Account : Premium
Version : 1.1.25.559.g85cf5e4c
OS : Windows 10 1909(18363.592)

same issue with @chris-kr

**Comment by bascurtiz** [comment] 2020-02-03 20:57
![image](https://user-images.githubusercontent.com/34075088/73690205-240a0600-46d0-11ea-987f-4ff6ab699bd8.png)

**Comment by CappeDiem** [comment] 2020-02-06 18:11
Same Issue
Account type: Free
version: 1.1.24.91.g4ca6d5eb
OS: Windows 10 1909(18363.628)
Tried every fix that was in the comments

**Comment by saitejal** [comment] 2020-02-22 07:00
Is there a way to log the crashes?

**Comment by meik97** [comment] 2020-02-22 19:32
No there is no way to log the crashes.

Also I suggest everyone to try the latest XSpotify version. It fixes the most crashes.

**Comment by AlvaroBeiro** [comment] 2020-02-27 10:20
For me, it crashes no matter the order in which I open them, and no matter if I'm playing a song or not.

Probably implementating a log could be helpful to see what's failing.

**Comment by Stebulous** [comment] 2020-02-27 21:08
Continues to crash on startup ive done all the methods above, it doesnt even show the xspotify logo text or anything just a blank console. Suggest adding logging feature.

**Comment by meik97** [comment] 2020-02-27 21:27
@Stebulous @AlvaroBeiro 
Make sure you are using the right version.
If you do not have the right version, you can download it on my discord.

Also, i will close this issue since it has outdated information

**Closed** 2020-02-27 21:27 UTC
Labels: bug, priority: high

**Comment by Stebulous** [comment] 2020-02-27 21:35
@meik97 im in the discord but the only downloads are the github releases :V
